### PR TITLE
Webpack compatibility

### PR DESCRIPTION
**Pull request by EddyVerbruggen**
Hey TJ,

Can you please merge this PR because I want to use the plugin in a webpacked app, and without this change that's impossible.

Thx,
Eddy

### CODE REVIEW

**Comment by EddyVerbruggen** [comment]
Hey @tjvantoll, I fully understand if you have other priorities, so if you can add me as a contributor to GitHub and grant me publish rights for the npm package, then I'll be more than happy to do this myself.

Thanks,
Eddy

**Comment by tjvantoll** [comment]
Hey @EddyVerbruggen,

Sorry for missing this :(

If you check your email you should have commit access now, and you should also have npm permissions. Go nuts 😄

**Comment by tjvantoll** [comment]
Also, for future reference, if you ping me by user name in an issue I’ll get with you pretty quickly. Without the ping though these things tend to get lost in my GitHub notifications.

**Comment by EddyVerbruggen** [comment]
Hey @tjvantoll, noted.

And thanks for the invitation! 🙏

**Pull request merged**
